###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mariadb:
        image: 'mariadb:10.3'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=dev
            - MYSQL_DATABASE=vending_machine_app
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        ports:
            - '12003:3306'

    mariadb_test:
        image: 'mariadb:10.3'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=dev
            - MYSQL_DATABASE=vending_machine_app_test
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        ports:
            - '12004:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        depends_on:
            - php-fpm

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        depends_on:
            - mariadb
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
